/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.github.com/APDevTeam/Movecraft")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }
}

dependencies {
    api(libs.org.jetbrains.annotations.java5)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.net.countercraft.movecraft)
    compileOnly(libs.com.sk89q.worldedit.worldedit.core)
    compileOnly(libs.com.sk89q.worldguard.worldguard.bukkit)
    system(libs.net.countercraft.movecraft.combat.movecraftcombat)
}

group = "net.countercraft.movecraft.worldguard"
version = "1.0.0_beta-3"
description = "Movecraft-WorldGuard"
java.sourceCompatibility = JavaVersion.VERSION_13

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
